# Generated by Django 4.2.4 on 2023-08-30 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_topico_pagina_topico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('classe', models.CharField(choices=[('GUERREIRO', 'Guerreiro'), ('ARQUEIRO', 'Arqueiro'), ('LANCEIRO', 'Lanceiro'), ('CLERIGO', 'Clérigo'), ('MAGO', 'Mago')], default='Guerreiro', max_length=128)),
                ('atributos', models.IntegerField()),
            ],
        ),
    ]
